## This file defines attributes of variable "site",
  # and can be used as "site.ATTR" in other files.
## All files (excluding subdirectories) in the same directory as _config.yml
  # will be element in the variable "site.pages".
## In each file in site.pages, the variable "page" indicates the file itself,
  # and its own attributes can therefore be applied.
  # The attributes should be defined at the very beginning of the file,
  # included in a pair of lines of "---".

# Site settings
# Variables here will appear as site.var in html files
# You can search "site.var" in the project and find where and how they are used
title: EM
UserName: Eicmlye # EM added
SEOTitle: Eicmlye | EM Blog
header-img: img/em/em-home-bg.png # this image will replace header image if other pages haven't got one
email: 5356682885@qq.com
description:
keyword: "EM, Eicmlye, EM Blog"
url: "http://Eicmlye.github.io"          # your host, absolute URL
baseurl:       # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Eicmlye/Eicmlye.github.io.git" # your code repository

# Sidebar settings
sidebar: true                           # true for enabling Sidebar.
sidebar-about-description: "Think only of the best. "
sidebar-avatar: /img/em/em-avatar.jpg   # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: false
# weibo_username:
# zhihu_username:     eicmlye   # all letters in lower case
github_username:    Eicmlye   # case sensitive
# facebook_username:
# jianshu_username:
# twitter_username:

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10        # numbers of posts per page shown on your homepage
# The directories and files below will not be included in the variable site.pages
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","exclude"]
anchorjs: true      # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

## 评论系统

# Disqus（https://disqus.com/）
# disqus_username:

# Gitalk
gitalk:
  enable: true    # true for enabling Gitalk Comments
  clientID: 7762445e689d50621b07                            # 生成的 clientID
  clientSecret: 7d90ed927fe36b7786ef9fa6bc97af93d000f795    # 生成的 clientSecret
  repo: Eicmlye.github.io    # 仓库名称
  owner: Eicmlye    # GitHub 用户名
  admin: Eicmlye
  distractionFreeMode: true # 是否启用类似 FB 的阴影遮罩

## 统计

# Analytics settings
# Baidu Analytics
ba_track_id:

# Google Analytics
ga_track_id:                 # Format: UA-xxxxxx-xx
ga_domain: auto              # 默认的是 auto, 也可改为自定义的域名

# Featured Tags
featured-tags: true                     # true for enabling homepage tag recommendation
featured-condition-size: 2              # least number of posts for a tag to be shown

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends: [
    {
        title: "Eicmlye",
        href: "http://Eicmlye.github.io"
    }
]
